#!/usr/bin/env python3
"""
Genera lyrics.ass (solo Kanji) y lyrics-fullbackup.ass (trilingüe) a partir de
lyrics-final.md con placeholder timings repartidos evenly.

Uso:
    python gen-ass.py <track-dir> <title> <track-num> <duration-sec>

Ejemplo:
    python gen-ass.py 02-恋のにゃんぱとる "恋のにゃんぱとる☆" 02 228
"""

import os
import re
import sys
from pathlib import Path

# Nombre del artista (para el header y los créditos). Se toma de KARAOKE_ARTIST.
ARTIST = os.environ.get("KARAOKE_ARTIST", "")


HEADER_TEMPLATE = """[Script Info]
; Script generated by gen-ass.py
Title: {artist} - {title} (track {track_num})
ScriptType: v4.00+
WrapStyle: 0
ScaledBorderAndShadow: yes
YCbCr Matrix: TV.709
PlayResX: 1920
PlayResY: 1080

[Aegisub Project Garbage]
Audio File: dummy.mp4
Video File: dummy.mp4
Video AR Mode: 4
Video AR Value: 1.778001
Video Zoom Percent: 0.500000
Active Line: 1
Video Position: 0

[V4+ Styles]
Format: Name, Fontname, Fontsize, PrimaryColour, SecondaryColour, OutlineColour, BackColour, Bold, Italic, Underline, StrikeOut, ScaleX, ScaleY, Spacing, Angle, BorderStyle, Outline, Shadow, Alignment, MarginL, MarginR, MarginV, Encoding
Style: Kanji,Noto Sans CJK JP,80,&H00C9D95F,&H00FFFFFF,&H00FFFFFF,&H64000000,-1,0,0,0,100,100,0,0,1,5,2,2,40,40,260,1
Style: Romaji,Noto Sans CJK JP,52,&H00C9D95F,&H00FFFFFF,&H00FFFFFF,&H64000000,0,-1,0,0,100,100,0,0,1,3.5,2,2,40,40,180,1
Style: Spanish,Noto Sans CJK JP,42,&H00C9D95F,&H00FFFFFF,&H00FFFFFF,&H64000000,0,0,0,0,100,100,0,0,1,3,2,2,40,40,100,1
Style: Title,Noto Sans CJK JP,90,&H00C9D95F,&H00FFFFFF,&H00FFFFFF,&H64000000,-1,0,0,0,100,100,0,0,1,6,3,2,40,40,400,1
Style: Credits,Noto Sans CJK JP,36,&H00C9D95F,&H00FFFFFF,&H00FFFFFF,&H64000000,0,-1,0,0,100,100,0,0,1,2.5,2,2,40,40,280,1

[Events]
Format: Layer, Start, End, Style, Name, MarginL, MarginR, MarginV, Effect, Text
"""


def secs_to_ass(s: float) -> str:
    h = int(s // 3600)
    m = int((s % 3600) // 60)
    s = s % 60
    return f"{h}:{m:02d}:{s:05.2f}"


def parse_lyrics_md(md_path: Path):
    """Devuelve lista de (section_name, [(jp, ro, es), ...])."""
    text = md_path.read_text(encoding="utf-8")
    sections = []
    current_section = None
    current_entries = []

    section_pat = re.compile(r"^## \[(.+)\]")
    block_pat = re.compile(
        r"```\s*\nJP:\s*(.+?)\nRO:\s*(.+?)\nES:\s*(.+?)\n```",
        re.DOTALL,
    )

    for line in text.splitlines():
        m = section_pat.match(line)
        if m:
            if current_section is not None:
                sections.append((current_section, current_entries))
            current_section = m.group(1)
            current_entries = []

    # Find blocks per section by splitting text on section headers
    text_after_first = text
    # Simpler: parse all blocks in order, then assign to sections by scanning
    sections = []
    section_starts = []
    for i, line in enumerate(text.splitlines()):
        m = section_pat.match(line)
        if m:
            section_starts.append((i, m.group(1)))

    lines = text.splitlines()
    for idx, (line_no, name) in enumerate(section_starts):
        end_line = section_starts[idx + 1][0] if idx + 1 < len(section_starts) else len(lines)
        chunk = "\n".join(lines[line_no:end_line])
        entries = []
        for jp, ro, es in block_pat.findall(chunk):
            entries.append((jp.strip(), ro.strip(), es.strip()))
        sections.append((name, entries))

    return sections


def generate_ass(track_dir: Path, title: str, track_num: str, duration: float, kanji_only: bool):
    md_path = track_dir / "lyrics-final.md"
    sections = parse_lyrics_md(md_path)

    total_lines = sum(len(entries) for _, entries in sections)
    if total_lines == 0:
        print("⚠️  No se encontraron entries en lyrics-final.md")
        return ""

    # Reservar 8s al inicio para intro instrumental, 5s final
    start_offset = 8.0
    end_offset = 5.0
    available = duration - start_offset - end_offset
    line_dur = available / total_lines

    output = HEADER_TEMPLATE.format(artist=ARTIST, title=title, track_num=track_num)

    # Title card (0-3s)
    output += f"Comment: 0,0:00:00.00,0:00:00.00,Kanji,,0,0,0,,=== TITLE CARD ===\n"
    output += f"Dialogue: 0,0:00:00.50,0:00:03.50,Title,,0,0,0,,{title}\n"
    output += f"Dialogue: 0,0:00:00.50,0:00:03.50,Credits,,0,0,0,,{ARTIST}\n"

    t = start_offset
    for section_name, entries in sections:
        output += f"Comment: 0,0:00:00.00,0:00:00.00,Kanji,,0,0,0,,=== {section_name.upper()} ===\n"
        for jp, ro, es in entries:
            start = secs_to_ass(t)
            end = secs_to_ass(t + line_dur)
            output += f"Dialogue: 0,{start},{end},Kanji,,0,0,0,,{jp}\n"
            if not kanji_only:
                output += f"Dialogue: 0,{start},{end},Romaji,,0,0,0,,{ro}\n"
                output += f"Dialogue: 0,{start},{end},Spanish,,0,0,0,,{es}\n"
            t += line_dur

    return output


def main():
    if len(sys.argv) != 5:
        print(__doc__)
        sys.exit(1)

    track_dir = Path(sys.argv[1])
    title = sys.argv[2]
    track_num = sys.argv[3]
    duration = float(sys.argv[4])

    # lyrics.ass: solo Kanji (input para whisper-to-ass)
    ass_kanji = generate_ass(track_dir, title, track_num, duration, kanji_only=True)
    (track_dir / "lyrics.ass").write_text(ass_kanji, encoding="utf-8")
    print(f"✓ Escrito: {track_dir}/lyrics.ass")

    # lyrics-fullbackup.ass: trilingüe (fuente para merge)
    ass_full = generate_ass(track_dir, title, track_num, duration, kanji_only=False)
    (track_dir / "lyrics-fullbackup.ass").write_text(ass_full, encoding="utf-8")
    print(f"✓ Escrito: {track_dir}/lyrics-fullbackup.ass")

    # Generar dummy.mp4 (cover + audio FLAC del track, baja calidad para Aegisub preview)
    import subprocess
    cover = Path(os.environ.get("COVER_IMAGE", Path(__file__).parent / "_shared" / "cover.jpg"))
    music_dir = Path(os.environ.get("MUSIC_DIR", ""))
    flacs = list(music_dir.glob(f"{track_num}.*.flac"))
    dummy_dst = track_dir / "dummy.mp4"
    if flacs and cover.exists() and not dummy_dst.exists():
        subprocess.run([
            "ffmpeg", "-loop", "1", "-framerate", "5", "-i", str(cover),
            "-i", str(flacs[0]),
            "-vf", "scale=960:540:force_original_aspect_ratio=decrease,pad=960:540:(ow-iw)/2:(oh-ih)/2:color=black",
            "-c:v", "libopenh264", "-b:v", "500k",
            "-c:a", "aac", "-b:a", "128k", "-shortest",
            "-y", str(dummy_dst)
        ], check=True, capture_output=True)
        print(f"✓ Generado: {dummy_dst}")


if __name__ == "__main__":
    main()
